### PR TITLE
Enable scala checkstyle in the spark module

### PR DESCRIPTION
**Pull request by maropu**
This pr is to apply the same scala-checkstyle with Spark and fix all the style errors trapped by the checker.

### CODE REVIEW

**Comment by oza** [comment]
+1, LGTM.

The diff seems to be large, but the change itself is clean:

* spark/spark-{1.6,2.0}/scalastyle-config.xml is moved to spark/spark-common/scalastyle-config.xml.
* spark/spark-{1.6,2.0}/dev/scalastyle is embedded into scalastyle-config.xml.
* Fixed checkstyle violations.

**Comment by maropu** [comment]
thx for your summary ;)

**Comment by myui** [comment]
LGTM. Merged. Please close JIRA issue. @oza

**Comment by oza** [comment]
done

**Pull request merged**
