### PR TITLE
Feature selection

### PR DESCRIPTION
**Pull request by myui**
based on PR #352 by @amaya382

### CODE REVIEW

**Comment by myui** [comment]
@amaya382 Could you provide usage in Markdown if possible? 

`docs/gitbook/ft_engineering/feature_selection.md` or so. Use `gitbook serve` to see the gitbook document.

It will be published as `3.5 Feature Selection` on 
http://hivemall.incubator.apache.org/userguide/

**Comment by amaya382** [comment]
@myui okay. do it on other branch from current develop

**Comment by myui** [comment]
@amaya382 you can fork this branch `feature_selection` and send PR to this branch. Thanks!

**Comment by myui** [comment]
@maropu or @amaya382 

Could you take a look at

```
error file=/home/travis/build/myui/hivemall/spark/spark-1.6/src/main/scala/org/apache/spark/sql/hive/GroupedDataEx.scala message=Expected token RBRACE but got Token(EOF,,11190,)
error file=/home/travis/build/myui/hivemall/spark/spark-1.6/src/main/scala/org/apache/spark/sql/hive/HivemallOps.scala message=Use Javadoc style indentation for multiline comments line=1012 column=0
error file=/home/travis/build/myui/hivemall/spark/spark-1.6/src/test/scala/org/apache/spark/sql/hive/HivemallOpsSuite.scala message=Expected token RBRACE but got Token(EOF,,24986,)
```

Scala formatting errors.
https://travis-ci.org/myui/hivemall/builds/177604541

**Comment by maropu** [comment]
@myui okay, I'll take it

**Comment by amaya382** [comment]
@myui plz check #386

**Comment by myui** [comment]
@amaya382 Thanks. Merged to this branch.

**Comment by maropu** [comment]
@myui fixed: https://github.com/maropu/hivemall/commit/8bb28ff743a46334d8a5333476bd6216cd05bb6f

**Comment by myui** [comment]
@maropu Cloud you send PR to this branch? Thanks.

**Comment by maropu** [comment]
@myui okay, I'll do.

**Comment by maropu** [comment]
See #387

**Comment by myui** [comment]
@amaya382 moved to https://github.com/apache/incubator-hivemall/pull/7

**Pull request closed without merging**
