### PR TITLE
Add Logarithmic Loss UDAF to evaluation functions

### PR DESCRIPTION
**Pull request by TakayukiSakai**
Added a function to calculate Logarithmic Loss for binary classification.

Definition: https://www.kaggle.com/wiki/LogarithmicLoss

This evaluation is used in some competitions on kaggle.
https://www.kaggle.com/c/criteo-display-ad-challenge
https://www.kaggle.com/c/sf-crime

### CODE REVIEW

**Comment by myui** [comment]
@TakayukiSakai Thanks. Will review your PR.

Linked https://github.com/myui/hivemall/issues/262

**Comment by myui** [comment]
@TakayukiSakai Did you run some tests? Please give us the test data if possible.

```
select 
   -sum(actual*LN(predicted)+(1-actual)*LN(1-predicted))/count(1) as logloss1
   logloss(actual, predicted) as logloss2
from
   preditected
```

**Comment by TakayukiSakai** [comment]
@myui I ran a test like this.

```
CREATE TABLE preditected (
  actual int,
  predicted double
);

INSERT INTO preditected VALUES (0, 0.01), (1, 0.02);

SELECT
   -SUM(actual*LN(predicted)+(1-actual)*LN(1-predicted))/count(1) as logloss1,
   logloss(predicted, actual) as logloss2
FROM
  preditected;

# logloss1 logloss2
# 1.9610366706408238 1.9610366706408238
```

Note that when a value of 'predicted' is 0 or 1, logloss1 can't be calculated because of the log function.

That's why I narrow the value of 'predicted' in [1e-15, 1 - 1e-15] here (https://github.com/TakayukiSakai/hivemall/blob/4944a6b1579d0f793b6a7d0d74158a927ace05c1/core/src/main/java/hivemall/evaluation/LogarithmicLossUDAF.java#L87-L89).

**Comment by myui** [comment]
@TakayukiSakai LGTM. Merged. Thanks.

**Pull request merged**
