### PR TITLE
Separate optimizer implementations from the core package

### PR DESCRIPTION
**Pull request by maropu**
This pr comes from #279.

### CODE REVIEW

**Comment by myui** [comment]
@maropu how about the progress? This PR is huge and high priority for me.

**Comment by maropu** [comment]
we need to discuss off-line on friday, maybe..

**Comment by maropu** [comment]
@myui fixed. could you check again?

**Comment by myui** [comment]
@maropu moved to https://github.com/apache/incubator-hivemall/pull/3

**Pull request closed without merging**
