### PR TITLE
Support graded ground truth in NDCG UDAF

### PR DESCRIPTION
**Pull request by takuti**
References:

- [Python implementation](https://gist.github.com/bwhite/3726239#file-rank_metrics-py-L152-L229)
- [Wikipedia](https://en.wikipedia.org/wiki/Discounted_cumulative_gain)

### CODE REVIEW

**Comment by myui** [comment]
@takuti unit test is failing. 

```
testNDCG(hivemall.evaluation.GradedResponsesMeasuresTest)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0.915571450536> but was:<0.9545081784471766>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:553)
	at org.junit.Assert.assertEquals(Assert.java:683)
	at hivemall.evaluation.GradedResponsesMeasuresTest.testNDCG(GradedResponsesMeasuresTest.java:41)
```

**Comment by takuti** [comment]
@myui Thanks for pointing out the failing. There were problems on the expected outputs and `TreeMap` keys, and now they have been fixed.

(status is still WIP)

**Comment by takuti** [comment]
### Interface

```
ndcg(array rankItems, array correctItems [, const int recommendSize = rankItems.size])
```

### Test on Hive

#### Binary NDCG

- `rankItems` &mdash; Ranked list of recommended item IDs
- `correctItems` &mdash; List of truth item IDs

```
hive> select * from dummy_truth;
dummy_truth.userid      dummy_truth.itemid
1       1
1       2
1       4
2       1
2       2
2       4
3       1
3       2
3       4

hive> select * from dummy_rec;
dummy_rec.userid        dummy_rec.itemid        dummy_rec.score
1       1       10.0
1       3       8.0
1       2       6.0
1       6       2.0
2       1       10.0
2       3       8.0
2       2       6.0
2       6       2.0
3       1       10.0
3       3       8.0
3       2       6.0
3       6       2.0
```

For each user, I've set the exactly same item IDs as [the unit test](https://github.com/takuti/hivemall/blob/07d1ad94a1411c45921273635f2df800d25c2ef9/core/src/test/java/hivemall/evaluation/BinaryResponsesMeasuresTest.java#L30-L37).

```sql
with truth as (
  select userid, collect_set(itemid) as truth
  from dummy_truth
  group by userid
),
rec as (
  select
    userid,
    map_values(to_ordered_map(score, itemid, true)) as rec,
    cast(count(itemid) as int) as max_k
  from dummy_rec
  group by userid
)
select ndcg(t1.rec, t2.truth, t1.max_k)
from rec t1
join truth t2 on (t1.userid = t2.userid)
;
```

- `ndcg(t1.rec, t2.truth, t1.max_k)` => **0.7039180890341349**
- `ndcg(t1.rec, t2.truth, 2)` => **0.6131471927654585**. 

Both of them equal to the expected NDCG in the unit test.

#### Graded NDCG

- `rankItems` &mdash; Ordered list of structs <relScore, itemID> for recommended items
- `correctItems` &mdash; Ordered list of relScores for truth items

```
hive> select * from dummy_recrel;
dummy_recrel.userid     dummy_recrel.itemid     dummy_recrel.score      dummy_recrel.relscore
1       1       10.0    5.0
1       3       8.0     2.0
1       2       6.0     4.0
1       6       2.0     1.0
1       4       1.0     3.0
2       1       10.0    5.0
2       3       8.0     2.0
2       2       6.0     4.0
2       6       2.0     1.0
2       4       1.0     3.0
3       1       10.0    5.0
3       3       8.0     2.0
3       2       6.0     4.0
3       6       2.0     1.0
3       4       1.0     3.0
```

Similarly to the binary case, each user has the same item-relScore pairs as [the unit test case](https://github.com/takuti/hivemall/blob/07d1ad94a1411c45921273635f2df800d25c2ef9/core/src/test/java/hivemall/evaluation/GradedResponsesMeasuresTest.java#L30-L37).

```sql
with truth as (
  select userid, map_keys(to_ordered_map(relscore, itemid, true)) as truth
  from dummy_recrel
  group by userid
),
rec as (
  select
    userid,
    map_values (
      to_ordered_map(score, struct(relscore, itemid), true)
    ) as rec,
    cast(count(itemid) as int) as max_k
  from dummy_recrel
  group by userid
)
select ndcg(t1.rec, t2.truth, 3)
from rec t1
join truth t2 on (t1.userid = t2.userid)
;
```

- `ndcg(t1.rec, t2.truth, 3)` => **0.9187707805346093**
- `ndcg(t1.rec, t2.truth, 2)` => **0.8128912838590544**

Also equal to the unit test.

**Comment by takuti** [comment]
@myui Removed [WIP] prefix from the title, and now I am ready for review.

**Pull request closed without merging**
