### PR TITLE
Support incremental compilation with zinc

### PR DESCRIPTION
**Pull request by maropu**
This pr is to enable incremental compilation with zinc.
Quick benchmark results are as follows;
```
### zinc enabled ###
./bin/mvn clean test-compile -- the first compilation
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Hivemall ........................................... SUCCESS [  0.074 s]
[INFO] Hivemall Core ...................................... SUCCESS [  6.066 s]
[INFO] Hivemall NLP ....................................... SUCCESS [  0.532 s]
[INFO] Hivemall Mix Server ................................ SUCCESS [  0.542 s]
[INFO] ------------------------------------------------------------------------

./bin/mvn test-compile -- the second one
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Hivemall ........................................... SUCCESS [  0.004 s]
[INFO] Hivemall Core ...................................... SUCCESS [  0.854 s]
[INFO] Hivemall NLP ....................................... SUCCESS [  0.131 s]
[INFO] Hivemall Mix Server ................................ SUCCESS [  0.122 s]
[INFO] ------------------------------------------------------------------------
```

```
### zinc disable ###
./bin/mvn clean test-compile -- the first compilation
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Hivemall ........................................... SUCCESS [  0.090 s]
[INFO] Hivemall Core ...................................... SUCCESS [  5.691 s]
[INFO] Hivemall NLP ....................................... SUCCESS [  0.785 s]
[INFO] Hivemall Mix Server ................................ SUCCESS [  0.533 s]
[INFO] ------------------------------------------------------------------------

./bin/mvn test-compile -- the second one
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Hivemall ........................................... SUCCESS [  0.007 s]
[INFO] Hivemall Core ...................................... SUCCESS [  1.274 s]
[INFO] Hivemall NLP ....................................... SUCCESS [  0.245 s]
[INFO] Hivemall Mix Server ................................ SUCCESS [  0.260 s]
[INFO] ------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by myui** [comment]
It seems the speedup by the incremental compilation is trivial for hivemall-level code size.

**Comment by maropu** [comment]
I think, the bigger main and test codes are, the slower total compile time is.
Also, this patch is to automatically fetch maven in the platforms that do not install it.
It is beneficial for novices to easily compile `hivemall`.

**Comment by myui** [comment]
1) Please rename bin/mvn to bin/mvn-zinc becuase it is confusing w/ existing mvn command

2) Move zinc entry of top-level pom.xml to spark/pom.xml becuase zinc's incremental compilation is useful only for slow Scala code compilation.

**Comment by maropu** [comment]
Okay, I removed zinc integration and I'll put this in the `/spark` module.
How about a script to automatically download maven, that is `/bin/mvn.sh`?

**Pull request closed without merging**
