### PR TITLE
Support HivemallOps on spark-v2.0

### PR DESCRIPTION
**Pull request by maropu**
This pr is to support Hivemall functions on the newest release of Apache Spark.

### CODE REVIEW

**Comment by myui** [comment]
Is it possible to have compatibilities to Spark `v1.6.x` ?
I guess major Hadoop/Spark distribution users are still using `v1.6.x`.

http://blog.cask.co/2015/06/hadoop-components-versions-in-distros-matrix/

**Comment by maropu** [comment]
To support both version, we need to have different codes for these version because they have no binary compatibility. Then, we switch the version by passing a `-P` profile option like;
`mvn package -Pspark-2.0` or `mvn package -Pspark-1.6`.

**Comment by maropu** [comment]
Not `-D` but `-P`.

**Comment by maropu** [comment]
please check this again?

**Comment by myui** [comment]
@maropu sure. Thanks.

**Comment by myui** [comment]
Merged. Well done. Thanks!

**Pull request merged**
