### PR TITLE
clean spark-common before building with spark

### PR DESCRIPTION
**Pull request by amaya382**
for resolving spark binary incompatibility between 1.6 and 2.0

### CODE REVIEW

**Comment by myui** [comment]
please review @maropu

**Comment by maropu** [comment]
thx for this work. btw, I meant we just added `clean` in `.travis.yml`.
```
script:
  - mvn -q test -Pspark-2.0
  # test the spark-1.6 module only in this second run
  - mvn -q **clean** test -Pspark-1.6 -Dtest=org.apache.spark.*
```
This fix is more reasonable than mine?

**Comment by amaya382** [comment]
@maropu hm... I think my fix makes also development in local(= out of CI) better. What do you think?

**Comment by maropu** [comment]
yea, okay. can you merge the two `build` enries into one? It's currently too duplicated.

**Comment by amaya382** [comment]
@maropu I agree, but it makes pom more complex because we cannot chain or inherit profiles...

**Comment by maropu** [comment]
How about moving this entry into `/spark-common/pom.xml`? It does not work?

**Comment by myui** [comment]
@maropu I think it's okey as it is.

**Comment by maropu** [comment]
I think this is not a good approach because we need to add this duplicated entry per spark feature release (every 3 or 4 months). BTW, `mvn -q test -Pspark-2.0; mvn -q test -Pspark-1.6 -Dtest=org.apache.spark.*` was passed in my environment. Anybody reproduce this?

**Comment by amaya382** [comment]
@myui @maropu I agree with maropu. Not only his reason, also it turns out unnecessary to use extra and non-flexible configuration to del *only* `spark-common/target`(there is no need to clean other modules)

**Comment by myui** [comment]
@maropu Happend again. Why seeing mvn repository for hivemall-spark? 

$ mvn -q test -Pspark-1.6 -Dtest=org.apache.spark.*
[ERROR] Failed to execute goal on project hivemall-spark: Could not resolve dependencies for project io.github.myui:hivemall-spark:jar:0.4.2-rc.2: Failed to collect dependencies at io.github.myui:hivemall-spark-common:jar:0.4.2-rc.2 -> org.apache.spark:spark-sql_2.11:jar:${spark.version}: Failed to read artifact descriptor for org.apache.spark:spark-sql_2.11:jar:${spark.version}: Could not transfer artifact org.apache.spark:spark-sql_2.11:pom:${spark.version} from/to sonatype-apache (https://repository.apache.org/releases/): Connect to repository.apache.org:443 [repository.apache.org/207.244.88.143] failed: Connection timed out -> [Help 1]

**Comment by maropu** [comment]
okay, I'll check later

**Comment by maropu** [comment]
I looked around to find better work-arounds though, I couldn't find. The apache infra frequently gets down, haha.

**Comment by myui** [comment]
Okey, merged thanks. @amaya382

**Comment by maropu** [comment]
@amaya382 Can you add comments there about why is the clean-up needed?

**Comment by amaya382** [comment]
@maropu added in #363, plz see it

**Pull request merged**
