### PR TITLE
Add the check-style of the hadoop configuration

### PR DESCRIPTION
**Pull request by maropu**
ISTM the current implementation does not have rigid formats; check-style throws up many errors; 
https://raw.githubusercontent.com/maropu/hivemall/CheckStyleResult/target/checkstyle-errors.xml
I think we need to discuss how to handle this issue.

### CODE REVIEW

**Comment by myui** [comment]
Please use Eclipse code formatter for IntelliJ.
https://github.com/krasa/EclipseCodeFormatter#instructions
https://github.com/myui/hivemall/blob/master/resources/eclipse_formatter.xml

**Comment by myui** [comment]
It might be better to use checkstyle and formatter: 
https://github.com/google/styleguide

We need to find a good one for us.

**Comment by maropu** [comment]
Ok, I try to make minimum rules for this initial commit.
Then, we will make the rules more strict step-by-step in following developments.

**Comment by maropu** [comment]
Made checkstyle.xml more simpler and fixed check-style errors in the setting.

**Comment by myui** [comment]
Found this one. http://eclipse-cs.sourceforge.net/

**Comment by myui** [comment]
Source code formatter is prepared for Eclipse and Idea.
https://github.com/myui/hivemall/tree/master/resources

Please apply `mvn formatter:format` before contributing patches.

Also, checkstyle is prepared while usnig it is optional.

**Pull request closed without merging**
